version: 2

# *****************
# Jobs
# *****************

jobs:

  # website
  website:
    docker: 
      - image: coxy1989/pandoc-aws
    steps:
      - checkout
      - run: 
          name: Convert markdown to html
          command: (cd website/content ; bash _convert_markdown_to_html.sh)
      - run:  
          name: Upload to s3 host
          command: (aws s3 cp website/content s3://bucket-host-website --exclude "*" --include "html/*" --include "css/*" --recursive)


# *****************
# Workflows
# *****************

workflows:
  version: 2
  master:
    jobs:

      # website
      - website:
          filters:
            branches:
              only:
                - master

